{
        "ip": "37.238.106.8",
            "country_code": "IQ",
                "country_name": "Iraq",
                    "region_name": "Baghdad",
                        "district": "Al Rusafa",
                            "city_name": "Baghdad",
                                "latitude": 33.34058,
                                    "longitude": 44.40088,
                                        "zip_code": "-",
                                            "time_zone": "+03:00",
                                                "asn": "203214",
                                                    "as": "Hulum Almustakbal Company for Communication Engineering and Services Ltd",
                                                        "as_info": {
                                                                "as_number": "203214",
                                                                        "as_name": "Hulum Almustakbal Company for Communication Engineering and Services Ltd",
                                                                                "as_domain": "hulumtele.com",
                                                                                        "as_usage_type": "ISP",
                                                                                                "as_cidr": "37.238.106.0\/32"
                                                                                                    },
                                                                                                        "isp": "Earthlink Telecommunications Equipment Trading & Services DMCC",
                                                                                                            "domain": "earthlink.iq",
                                                                                                                "net_speed": "DSL",
                                                                                                                    "idd_code": "964",
                                                                                                                        "area_code": "01",
                                                                                                                            "weather_station_code": "IZXX0008",
                                                                                                                                "weather_station_name": "Baghdad",
                                                                                                                                    "mcc": "-",
                                                                                                                                        "mnc": "-",
                                                                                                                                            "mobile_brand": "-",
                                                                                                                                                "elevation": 37,
                                                                                                                                                    "usage_type": "ISP",
                                                                                                                                                        "address_type": "Unicast",
                                                                                                                                                            "ads_category": "IAB19-18",
                                                                                                                                                                "ads_category_name": "Internet Technology",
                                                                                                                                                                    "continent": {
                                                                                                                                                                            "name": "Asia",
                                                                                                                                                                                    "code": "AS",
                                                                                                                                                                                            "hemisphere": [
                                                                                                                                                                                                        "north",
                                                                                                                                                                                                                    "east"
                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                    "translation": {
                                                                                                                                                                                                                                                "lang": null,
                                                                                                                                                                                                                                                            "value": null
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                            "country": {
                                                                                                                                                                                                                                                                                    "name": "Iraq",
                                                                                                                                                                                                                                                                                            "alpha3_code": "IRQ",
                                                                                                                                                                                                                                                                                                    "numeric_code": 368,
                                                                                                                                                                                                                                                                                                            "demonym": "Iraqis",
                                                                                                                                                                                                                                                                                                                    "flag": "https:\/\/cdn.ip2location.io\/assets\/img\/flags\/iq.png",
                                                                                                                                                                                                                                                                                                                            "capital": "Baghdad",
                                                                                                                                                                                                                                                                                                                                    "total_area": 438317,
                                                                                                                                                                                                                                                                                                                                            "population": 41266109,
                                                                                                                                                                                                                                                                                                                                                    "currency": {
                                                                                                                                                                                                                                                                                                                                                                "code": "IQD",
                                                                                                                                                                                                                                                                                                                                                                            "name": "Iraqi Dinar",
                                                                                                                                                                                                                                                                                                                                                                                        "symbol": "\u062f.\u0639"
                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                        "language": {
                                                                                                                                                                                                                                                                                                                                                                                                                    "code": "AR",
                                                                                                                                                                                                                                                                                                                                                                                                                                "name": "Arabic"
                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                "tld": "iq",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "translation": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "lang": null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "value": null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "region": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "name": "Baghdad",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "code": "IQ-BG",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "translation": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "lang": null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "value": null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "city": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "name": "Baghdad",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "translation": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "lang": null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "value": null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "time_zone_info": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "olson": "Asia\/Baghdad",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "current_time": "2025-11-03T20:57:15+03:00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "gmt_offset": 10800,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "is_dst": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "abbreviation": "AST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "dst_start_date": null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "dst_end_date": null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "sunrise": "06:21",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "sunset": "17:10"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "geotargeting": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "metro": null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "is_proxy": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "fraud_score": 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "proxy": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "last_seen": 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "proxy_type": "-",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "threat": "-",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "provider": "-",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "is_vpn": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "is_tor": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "is_data_center": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "is_public_proxy": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "is_web_proxy": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "is_web_crawler": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "is_residential_proxy": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "is_consumer_privacy_network": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "is_enterprise_private_network": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "is_spammer": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "is_scanner": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "is_botnet": false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "is_bogon": false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
